version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: blog_engine_db
    environment:
      - POSTGRES_DB=blog_engine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
